"""Verify every template loads, validates defaults, and renders."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scadgen.core.template_registry import TemplateRegistry
from scadgen.core.renderer import SCADRenderer

TEMPLATES_DIR = str(Path(__file__).resolve().parent.parent / "scadgen" / "templates")

EXPECTED_TEMPLATES = [
    "bushing", "cone", "cube", "cylinder", "gear_spur",
    "hex_bolt", "hex_nut", "sphere", "torus",
]


def get_registry():
    return TemplateRegistry([TEMPLATES_DIR])


def test_all_templates_discovered():
    registry = get_registry()
    ids = registry.all_ids()
    for expected in EXPECTED_TEMPLATES:
        assert expected in ids, f"Template '{expected}' not found. Got: {ids}"


def test_all_templates_have_params():
    registry = get_registry()
    for tid in EXPECTED_TEMPLATES:
        tmpl = registry.get(tid)
        assert len(tmpl.parameters) > 0, f"{tid} has no parameters"
        assert tmpl.module_name, f"{tid} has no module_name"
        assert tmpl.description, f"{tid} has no description"


def test_all_templates_render_with_defaults():
    registry = get_registry()
    renderer = SCADRenderer()
    for tid in EXPECTED_TEMPLATES:
        tmpl = registry.get(tid)
        defaults = tmpl.apply_defaults({})
        scad = renderer.render(tmpl, defaults)
        assert tmpl.module_name in scad, f"{tid}: module call not in output"
        assert "Generated by SCADgen" in scad, f"{tid}: header missing"
        assert "/* [Parameters] */" in scad, f"{tid}: Customizer block missing"


def test_alias_lookup():
    registry = get_registry()
    assert registry.get("bolt").template_id == "hex_bolt"
    assert registry.get("gear").template_id == "gear_spur"
    assert registry.get("nut").template_id == "hex_nut"
    assert registry.get("cog").template_id == "gear_spur"


def test_parameter_validation():
    registry = get_registry()
    gear = registry.get("gear_spur")
    validated = gear.validate_params({"teeth": "32", "modul": "2.5"})
    assert validated["teeth"] == 32
    assert validated["modul"] == 2.5


def test_derived_values():
    registry = get_registry()
    gear = registry.get("gear_spur")
    params = gear.apply_defaults({"teeth": 32, "modul": 2.0})
    derived = gear.compute_derived(params)
    assert "pitch_diameter" in derived
    assert derived["pitch_diameter"] == 64.0
    assert derived["outer_diameter"] == 68.0


def test_gear_render_no_difference_bug():
    registry = get_registry()
    renderer = SCADRenderer()
    gear = registry.get("gear_spur")
    params = gear.apply_defaults({"teeth": 32, "modul": 2.5, "thickness": 10})
    scad = renderer.render(gear, params)
    # The old bug: difference(teeth=32, ...). This must never appear.
    assert "difference(teeth" not in scad
    assert "difference(modul" not in scad
    # The call line must be at the end, targeting gear_spur
    lines = scad.strip().splitlines()
    call_line = lines[-1]
    assert call_line.startswith("gear_spur(")


if __name__ == "__main__":
    test_all_templates_discovered()
    test_all_templates_have_params()
    test_all_templates_render_with_defaults()
    test_alias_lookup()
    test_parameter_validation()
    test_derived_values()
    test_gear_render_no_difference_bug()
    print("All template tests passed!")
