"""Assembly renderer — generates a single .scad file for a positioned assembly."""

from __future__ import annotations

from typing import Any

from scadgen.assembly.part import Part, Transform

if False:  # TYPE_CHECKING
    from scadgen.assembly.assembly import Assembly

_DEFAULT_PALETTE = [
    "Silver", "SteelBlue", "DarkGray", "Goldenrod", "IndianRed",
    "CadetBlue", "DarkSeaGreen", "Peru", "SlateGray", "Olive",
    "Sienna", "Teal", "Khaki", "Coral", "MediumPurple", "Tan",
]


def render_assembly(
    assembly: Assembly,
    transforms: dict[str, Transform],
    colors: dict[str, str] | None = None,
) -> str:
    if colors is None:
        colors = {}
    parts_ordered = list(assembly.parts.values())

    sections = [
        _header(assembly, len(parts_ordered)),
        _module_definitions(parts_ordered),
        _bom(parts_ordered),
        _positioned_parts(parts_ordered, transforms, colors),
    ]
    return "\n".join(sections)


def _header(assembly: Assembly, count: int) -> str:
    return (
        f"// Assembly: {assembly.assembly_id}\n"
        f"// Generated by SCADgen Assembly Engine\n"
        f"// Parts: {count}\n"
    )


def _module_definitions(parts: list[Part]) -> str:
    seen: set[str] = set()
    blocks: list[str] = []
    for p in parts:
        tid = p.template.template_id
        if tid in seen:
            continue
        seen.add(tid)
        source = p.template.source_code.rstrip()
        blocks.append(source)
    if not blocks:
        return ""
    return (
        "// ── Module definitions ──────────────────────────────────\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def _bom(parts: list[Part]) -> str:
    lines = ["", "// ── Bill of Materials ───────────────────────────────────"]
    for i, p in enumerate(parts, 1):
        key_params = _key_params_str(p)
        lines.append(f"// {i}. {p.part_id} ({p.template.template_id}) — {key_params}")
    lines.append("")
    return "\n".join(lines)


def _key_params_str(part: Part) -> str:
    items: list[str] = []
    for pd in part.template.parameters:
        if pd.name == "fn":
            continue
        val = part.parameters.get(pd.name, pd.default)
        items.append(f"{pd.name}={_fmt(val, pd.type)}")
        if len(items) >= 5:
            break
    return ", ".join(items)


def _positioned_parts(
    parts: list[Part],
    transforms: dict[str, Transform],
    colors: dict[str, str],
) -> str:
    lines = ["// ── Assembly ────────────────────────────────────────────", ""]
    for i, p in enumerate(parts):
        tf = transforms.get(p.part_id, Transform.identity())
        color = colors.get(p.part_id, _DEFAULT_PALETTE[i % len(_DEFAULT_PALETTE)])
        call = _build_call(p)

        lines.append(f"// Part: {p.part_id} ({p.template.template_id})")
        modifier = ""
        if color.startswith("%"):
            modifier = "% "
            color = color[1:]
        if ":" in color:
            cname, alpha = color.rsplit(":", 1)
            lines.append(f'{modifier}color("{cname}", {alpha})')
        else:
            lines.append(f'{modifier}color("{color}")')

        tx, ty, tz = tf.translation
        rx, ry, rz = tf.rotation
        has_rot = any(abs(v) > 1e-9 for v in tf.rotation)

        lines.append(f"translate([{_n(tx)}, {_n(ty)}, {_n(tz)}])")
        if has_rot:
            lines.append(f"rotate([{_n(rx)}, {_n(ry)}, {_n(rz)}])")
        lines.append(f"  {call}")
        lines.append("")
    return "\n".join(lines)


def _build_call(part: Part) -> str:
    args: list[str] = []
    for pd in part.template.parameters:
        val = part.parameters.get(pd.name, pd.default)
        args.append(f"{pd.name}={_fmt(val, pd.type)}")
    return f"{part.template.module_name}({', '.join(args)});"


def _fmt(value: Any, param_type: str) -> str:
    if param_type == "bool":
        return "true" if value else "false"
    if param_type == "int":
        return str(int(float(value)))
    if param_type == "float":
        return f"{float(value):.4g}"
    if param_type == "string":
        return f'"{value}"'
    return str(value)


def _n(v: float) -> str:
    if abs(v) < 1e-9:
        return "0"
    if v == int(v):
        return str(int(v))
    return f"{v:.4g}"
