// Assembly: assembly
// Generated by SCADgen Assembly Engine
// Parts: 5

// ── Module definitions ──────────────────────────────────

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: cylinder
// module_name: cylinder_shape
// description: Cylinder or tube (hollow when inner_diam > 0), with optional cutter mode
// category: primitive
// tags: [cylinder, tube, pipe, rod, shaft, hollow]
// aliases: [cylinder, tube, pipe]
// keywords: [cylinder, tube, pipe, hollow, bore, diameter, height, wall]
// length_param: height
// params:
//   - name: diam
//     type: float
//     default: 20.0
//     min: 0.1
//     max: 2000.0
//     unit: mm
//     description: Outer diameter
//   - name: height
//     type: float
//     default: 40.0
//     min: 0.1
//     max: 2000.0
//     unit: mm
//     description: Height
//   - name: center
//     type: bool
//     default: false
//     description: Center vertically on origin
//   - name: inner_diam
//     type: float
//     default: 0.0
//     min: 0.0
//     max: 2000.0
//     unit: mm
//     description: Inner diameter (0 = solid, >0 = tube)
//   - name: as_cutter
//     type: bool
//     default: false
//     description: Overshoot ends for boolean subtraction
//   - name: overshoot
//     type: float
//     default: 0.3
//     min: 0.0
//     max: 5.0
//     unit: mm
//     description: Overshoot amount in cutter mode
//   - name: fn
//     type: int
//     default: 96
//     min: 16
//     max: 512
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: center_axis
//     type: axial
//     origin: [0, 0, "height / 2"]
//     direction: [0, 0, 1]
//     diameter_ref: diam
//   - name: top_face
//     type: planar
//     origin: [0, 0, "height"]
//     direction: [0, 0, 1]
//     diameter_ref: diam
//   - name: bottom_face
//     type: planar
//     origin: [0, 0, 0]
//     direction: [0, 0, -1]
//     diameter_ref: diam
// constraints:
//   - check: "inner_diam <= 0 or diam > inner_diam"
//     message: "Outer diameter ({diam}mm) must exceed inner diameter ({inner_diam}mm) for tube mode"
//     severity: error
// SCADGEN_META_END

module cylinder_shape(diam=20, height=40, center=false,
                      inner_diam=0, as_cutter=false,
                      overshoot=0.3, fn=96)
{
    $fn = fn;

    extra_h = as_cutter ? (height + 2*overshoot) : height;
    z_shift = as_cutter ? (center ? 0 : -overshoot) : 0;

    if (inner_diam <= 0) {
        translate([0,0,z_shift])
            cylinder(h = extra_h, d = diam, center = center);
    }
    else {
        difference() {
            translate([0,0,z_shift])
                cylinder(h = extra_h, d = diam, center = center);

            inner_extra_h = height + 2*overshoot;
            inner_shift   = center ? 0 : -overshoot;
            translate([0,0,inner_shift])
                cylinder(h = inner_extra_h, d = inner_diam, center = center);
        }
    }
}

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: torus
// module_name: torus_shape
// description: Parametric torus (ring shape)
// category: primitive
// tags: [torus, ring, donut, o-ring]
// aliases: [torus, ring, donut]
// keywords: [torus, ring, donut, major, minor, tube, o-ring]
// params:
//   - name: major_r
//     type: float
//     default: 25.0
//     min: 0.5
//     max: 1000.0
//     unit: mm
//     description: Major radius (center of tube path)
//   - name: minor_r
//     type: float
//     default: 6.0
//     min: 0.1
//     max: 500.0
//     unit: mm
//     description: Minor radius (tube cross-section)
//   - name: fn
//     type: int
//     default: 120
//     min: 16
//     max: 512
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: center_axis
//     type: axial
//     origin: [0, 0, 0]
//     direction: [0, 0, 1]
//   - name: top_face
//     type: planar
//     origin: [0, 0, "minor_r"]
//     direction: [0, 0, 1]
//   - name: bottom_face
//     type: planar
//     origin: [0, 0, "-minor_r"]
//     direction: [0, 0, -1]
// constraints:
//   - check: "major_r > minor_r"
//     message: "Major radius ({major_r}mm) must exceed minor radius ({minor_r}mm) to avoid self-intersection"
//     severity: error
// SCADGEN_META_END

module torus_shape(major_r=25, minor_r=6, fn=120) {
    $fn = fn;
    rotate_extrude(angle = 360)
        translate([major_r, 0, 0])
            circle(r = minor_r);
}

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: cage_dome
// module_name: cage_dome
// description: Domed wire-frame top of the birdcage, curving upward from the top ring to a rounded apex
// category: decorative/birdcage
// tags: [cage, dome, birdcage, wireframe, canopy, roof]
// aliases: [cage top, dome top, birdcage roof, wire dome, canopy]
// keywords: [birdcage, dome, wire, rib, cage, roof, canopy, apex, curved, frame]
// length_param: height
// params:
//   - name: base_diam
//     type: float
//     default: 190.0
//     min: 20.0
//     max: 2000.0
//     unit: mm
//     description: Diameter of the base ring where the dome meets the top ring
//   - name: height
//     type: float
//     default: 90.0
//     min: 10.0
//     max: 1000.0
//     unit: mm
//     description: Height of the dome from base ring to apex
//   - name: rib_diam
//     type: float
//     default: 3.0
//     min: 0.5
//     max: 30.0
//     unit: mm
//     description: Diameter of the wire ribs and base ring
//   - name: rib_count
//     type: int
//     default: 16
//     min: 4
//     max: 64
//     unit: count
//     description: Number of vertical wire ribs around the dome
//   - name: ring_count
//     type: int
//     default: 2
//     min: 0
//     max: 10
//     unit: count
//     description: Number of horizontal bracing rings crossing the ribs
//   - name: apex_diam
//     type: float
//     default: 10.0
//     min: 2.0
//     max: 100.0
//     unit: mm
//     description: Diameter of the rounded apex cap where ribs converge
//   - name: dome_segments
//     type: int
//     default: 12
//     min: 3
//     max: 48
//     unit: count
//     description: Number of segments used to approximate the curved rib profile
//   - name: fn
//     type: int
//     default: 64
//     min: 16
//     max: 256
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: bottom_face
//     type: planar
//     origin: [0, 0, 0]
//     direction: [0, 0, -1]
//   - name: top_face
//     type: planar
//     origin: [0, 0, "height"]
//     direction: [0, 0, 1]
// derived:
//   - base_radius: "base_diam / 2"
// constraints:
//   - check: "rib_diam < base_diam / 10"
//     message: "Rib diameter ({rib_diam}mm) is very thick relative to base diameter ({base_diam}mm)"
//     severity: warning
//   - check: "apex_diam < base_diam / 2"
//     message: "Apex diameter ({apex_diam}mm) should be smaller than half the base diameter ({base_diam}mm)"
//     severity: warning
//   - check: "height > 0 and base_diam > 0"
//     message: "Height and base diameter must both be positive"
//     severity: error
//   - check: "ring_count <= 10"
//     message: "Ring count ({ring_count}) is unusually high and may slow rendering"
//     severity: warning
// SCADGEN_META_END

module cage_dome(base_diam=190, height=90, rib_diam=3, rib_count=16,
                  ring_count=2, apex_diam=10, dome_segments=12, fn=64)
{
    $fn = fn;

    base_r = base_diam / 2;

    // Dome profile (quarter-circle-like curve) parameterized by t in [0,1]
    // t=0 -> base ring (r=base_r, z=0)
    // t=1 -> apex (r=0, z=height)
    function dome_radius(t) = base_r * cos(t * 90);
    function dome_z(t)      = height  * sin(t * 90);

    union() {

        // Vertical wire ribs curving from base ring up to apex
        for (i = [0 : rib_count - 1]) {
            rotate([0, 0, i * 360 / rib_count])
                cage_dome_rib(base_r, height, rib_diam, dome_segments);
        }

        // Horizontal bracing rings at intermediate heights
        if (ring_count > 0) {
            for (j = [1 : ring_count]) {
                t = j / (ring_count + 1);
                r = dome_radius(t);
                z = dome_z(t);
                translate([0, 0, z])
                    rotate_extrude()
                        translate([r, 0, 0])
                            circle(d = rib_diam * 0.85);
            }
        }

        // Rounded apex cap where all ribs converge
        translate([0, 0, height])
            sphere(d = apex_diam);

        // Base ring connecting to the top ring below
        rotate_extrude()
            translate([base_r, 0, 0])
                circle(d = rib_diam);
    }
}

// Single curved rib built from hulled sphere joints along the dome profile
module cage_dome_rib(base_r, height, rib_diam, segments)
{
    for (s = [0 : segments - 1]) {
        t0 = s / segments;
        t1 = (s + 1) / segments;

        p0 = [ base_r * cos(t0 * 90), 0, height * sin(t0 * 90) ];
        p1 = [ base_r * cos(t1 * 90), 0, height * sin(t1 * 90) ];

        hull() {
            translate(p0) sphere(d = rib_diam);
            translate(p1) sphere(d = rib_diam);
        }
    }
}

cage_dome();

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: sphere
// module_name: sphere_shape
// description: Parametric sphere
// category: primitive
// tags: [sphere, ball, round]
// aliases: [sphere, ball]
// keywords: [sphere, ball, round, diameter, radius]
// params:
//   - name: diam
//     type: float
//     default: 30.0
//     min: 0.1
//     max: 2000.0
//     unit: mm
//     description: Sphere diameter
//   - name: fn
//     type: int
//     default: 96
//     min: 16
//     max: 512
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: center_axis
//     type: axial
//     origin: [0, 0, 0]
//     direction: [0, 0, 1]
//     diameter_ref: diam
//   - name: top
//     type: axial
//     origin: [0, 0, "diam / 2"]
//     direction: [0, 0, 1]
//   - name: bottom
//     type: axial
//     origin: [0, 0, "-diam / 2"]
//     direction: [0, 0, -1]
// SCADGEN_META_END

module sphere_shape(diam=30, fn=96) {
    $fn = fn;
    sphere(d = diam);
}


// ── Bill of Materials ───────────────────────────────────
// 1. base (cylinder) — diam=200, height=12, center=false, inner_diam=0, as_cutter=false
// 2. cage_bars (cylinder) — diam=4, height=180, center=false, inner_diam=0, as_cutter=false
// 3. top_ring (torus) — major_r=90, minor_r=4
// 4. dome (cage_dome) — base_diam=190, height=90, rib_diam=3, rib_count=16, ring_count=2
// 5. finial (sphere) — diam=20

// ── Assembly ────────────────────────────────────────────

// Part: base (cylinder)
color("Silver")
translate([0, 0, 0])
  cylinder_shape(diam=200, height=12, center=false, inner_diam=0, as_cutter=false, overshoot=0.3, fn=96);

// Part: cage_bars (cylinder)
color("Silver")
translate([0, 0, 12])
  for (i = [0 : 15]) rotate([0, 0, i * 22.5]) translate([90, 0, 0]) cylinder_shape(diam=4, height=180, center=false, inner_diam=0, as_cutter=false, overshoot=0.3, fn=96);

// Part: top_ring (torus)
color("Silver")
translate([0, 0, 196])
  torus_shape(major_r=90, minor_r=4, fn=120);

// Part: dome (cage_dome)
color("Silver")
translate([0, 0, 200])
  cage_dome(base_diam=190, height=90, rib_diam=3, rib_count=16, ring_count=2, apex_diam=10, dome_segments=12, fn=64);

// Part: finial (sphere)
color("Goldenrod")
translate([0, 0, 300])
  sphere_shape(diam=20, fn=96);
