// Assembly: assembly
// Generated by SCADgen Assembly Engine
// Parts: 3

// ── Module definitions ──────────────────────────────────

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: lamp_base
// module_name: lamp_base
// description: Weighted circular lamp base with chamfered top edge
// category: lamp
// tags: [lamp, base, desk lamp, lighting]
// aliases: [lamp base, desk lamp base]
// keywords: [lamp, base, desk, light, stand, puck, weighted]
// length_param: height
// params:
//   - name: diameter
//     type: float
//     default: 130.0
//     min: 50.0
//     max: 300.0
//     unit: mm
//     description: Base outer diameter
//   - name: height
//     type: float
//     default: 18.0
//     min: 8.0
//     max: 50.0
//     unit: mm
//     description: Base height
//   - name: stem_hole_diam
//     type: float
//     default: 12.0
//     min: 5.0
//     max: 30.0
//     unit: mm
//     description: Center hole diameter for stem pass-through
//   - name: chamfer
//     type: float
//     default: 2.0
//     min: 0.5
//     max: 8.0
//     unit: mm
//     description: Top edge chamfer height
//   - name: fn
//     type: int
//     default: 128
//     min: 32
//     max: 512
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: stem_mount
//     type: axial
//     origin: [0, 0, "height"]
//     direction: [0, 0, 1]
//     diameter_ref: stem_hole_diam
//   - name: bottom_face
//     type: planar
//     origin: [0, 0, 0]
//     direction: [0, 0, -1]
// constraints:
//   - check: "stem_hole_diam < diameter * 0.3"
//     message: "Stem hole ({stem_hole_diam}mm) too large for base diameter ({diameter}mm)"
//     severity: error
//   - check: "chamfer < height / 2"
//     message: "Chamfer ({chamfer}mm) exceeds half the base height ({height}mm)"
//     severity: error
// SCADGEN_META_END

module lamp_base(diameter=130, height=18, stem_hole_diam=12, chamfer=2, fn=128)
{
    $fn = fn;

    difference() {
        union() {
            cylinder(h = height - chamfer, d = diameter);
            translate([0, 0, height - chamfer])
                cylinder(h = chamfer, d1 = diameter, d2 = diameter - chamfer * 2);
            cylinder(h = chamfer, d1 = diameter - chamfer * 2, d2 = diameter);
        }

        // Anti-slip rubber ring recess on bottom
        translate([0, 0, -0.1])
            difference() {
                cylinder(h = 1.1, d = diameter - 10);
                cylinder(h = 1.1, d = diameter - 20);
            }
    }

    // Switch detail on side
    translate([diameter / 2 - 1.5, -4, height * 0.3])
        cube([3, 8, 6]);
}

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: lamp_arm
// module_name: lamp_arm
// description: Gooseneck lamp arm with smooth quarter-circle curve at top
// category: lamp
// tags: [lamp, arm, gooseneck, stem, desk lamp]
// aliases: [lamp arm, gooseneck, lamp stem]
// keywords: [lamp, arm, gooseneck, stem, tube, curve, bend, neck, desk]
// length_param: straight_height
// params:
//   - name: stem_diam
//     type: float
//     default: 10.0
//     min: 4.0
//     max: 25.0
//     unit: mm
//     description: Arm tube diameter
//   - name: straight_height
//     type: float
//     default: 260.0
//     min: 50.0
//     max: 600.0
//     unit: mm
//     description: Height of the straight vertical section
//   - name: curve_radius
//     type: float
//     default: 55.0
//     min: 15.0
//     max: 150.0
//     unit: mm
//     description: Radius of the gooseneck bend
//   - name: joint_diam
//     type: float
//     default: 18.0
//     min: 8.0
//     max: 40.0
//     unit: mm
//     description: Shade joint ball diameter
//   - name: collar_diam
//     type: float
//     default: 18.0
//     min: 8.0
//     max: 40.0
//     unit: mm
//     description: Base collar diameter
//   - name: collar_height
//     type: float
//     default: 6.0
//     min: 2.0
//     max: 20.0
//     unit: mm
//     description: Base collar height
//   - name: fn
//     type: int
//     default: 64
//     min: 16
//     max: 256
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: base_end
//     type: axial
//     origin: [0, 0, 0]
//     direction: [0, 0, -1]
//     diameter_ref: stem_diam
//   - name: shade_mount
//     type: axial
//     origin: ["curve_radius", 0, "straight_height + curve_radius"]
//     direction: [0.34, 0, -0.94]
// constraints:
//   - check: "joint_diam >= stem_diam"
//     message: "Joint diameter ({joint_diam}mm) should be at least as large as stem ({stem_diam}mm)"
//     severity: warning
//   - check: "curve_radius > stem_diam * 2"
//     message: "Curve radius ({curve_radius}mm) too tight for stem diameter ({stem_diam}mm)"
//     severity: error
// SCADGEN_META_END

module lamp_arm(stem_diam=10, straight_height=260, curve_radius=55,
                joint_diam=18, collar_diam=18, collar_height=6, fn=64)
{
    $fn = fn;
    curve_steps = 24;

    // Base collar
    cylinder(h = collar_height, d1 = collar_diam, d2 = stem_diam);

    // Straight vertical section
    cylinder(h = straight_height, d = stem_diam);

    // Curved section — quarter circle in XZ plane
    for (i = [0 : curve_steps - 1]) {
        a1 = i * 90 / curve_steps;
        a2 = (i + 1) * 90 / curve_steps;
        hull() {
            translate([curve_radius * (1 - cos(a1)), 0,
                       straight_height + curve_radius * sin(a1)])
                sphere(d = stem_diam);
            translate([curve_radius * (1 - cos(a2)), 0,
                       straight_height + curve_radius * sin(a2)])
                sphere(d = stem_diam);
        }
    }

    // Joint ball at shade mount point
    translate([curve_radius, 0, straight_height + curve_radius])
        sphere(d = joint_diam);

    // Thumbscrew knobs on joint (decorative)
    translate([curve_radius, 0, straight_height + curve_radius])
        rotate([90, 0, 0])
            cylinder(h = joint_diam * 0.7, d = joint_diam * 0.35, center = true);
}

// SCADGEN_META_BEGIN
// schema_version: 1
// template_id: lamp_shade
// module_name: lamp_shade
// description: Truncated cone lamp shade with rolled rim and socket collar
// category: lamp
// tags: [lamp, shade, lampshade, desk lamp, cone]
// aliases: [lamp shade, lampshade, shade]
// keywords: [lamp, shade, cone, bell, light, desk, reflector, hood]
// length_param: height
// params:
//   - name: top_diam
//     type: float
//     default: 52.0
//     min: 15.0
//     max: 120.0
//     unit: mm
//     description: Narrow top opening diameter
//   - name: bottom_diam
//     type: float
//     default: 115.0
//     min: 40.0
//     max: 250.0
//     unit: mm
//     description: Wide bottom opening diameter
//   - name: height
//     type: float
//     default: 85.0
//     min: 20.0
//     max: 200.0
//     unit: mm
//     description: Shade height (cone section)
//   - name: thickness
//     type: float
//     default: 1.5
//     min: 0.5
//     max: 5.0
//     unit: mm
//     description: Shade wall thickness
//   - name: collar_height
//     type: float
//     default: 10.0
//     min: 3.0
//     max: 30.0
//     unit: mm
//     description: Top collar/socket height
//   - name: collar_diam
//     type: float
//     default: 22.0
//     min: 8.0
//     max: 50.0
//     unit: mm
//     description: Top collar outer diameter
//   - name: rim_height
//     type: float
//     default: 3.0
//     min: 1.0
//     max: 10.0
//     unit: mm
//     description: Bottom rim roll thickness
//   - name: fn
//     type: int
//     default: 128
//     min: 32
//     max: 512
//     unit: count
//     description: Circle resolution
// connectors:
//   - name: socket
//     type: axial
//     origin: [0, 0, "height + collar_height"]
//     direction: [0, 0, 1]
//     diameter_ref: collar_diam
// constraints:
//   - check: "bottom_diam > top_diam"
//     message: "Bottom diameter ({bottom_diam}mm) must exceed top diameter ({top_diam}mm)"
//     severity: error
//   - check: "collar_diam <= top_diam"
//     message: "Collar diameter ({collar_diam}mm) exceeds top opening ({top_diam}mm)"
//     severity: error
// SCADGEN_META_END

module lamp_shade(top_diam=52, bottom_diam=115, height=85,
                  thickness=1.5, collar_height=10, collar_diam=22,
                  rim_height=3, fn=128)
{
    $fn = fn;
    t = thickness;

    difference() {
        union() {
            cylinder(h = height, d1 = bottom_diam, d2 = top_diam);

            // Bottom rim roll (thickened edge ring)
            rotate_extrude()
                translate([bottom_diam / 2 - rim_height / 2, rim_height / 2, 0])
                    circle(d = rim_height);
        }

        // Inner hollow
        translate([0, 0, t])
            cylinder(h = height, d1 = bottom_diam - 2 * t, d2 = top_diam - 2 * t);
    }

    // Top collar / socket mount
    translate([0, 0, height]) {
        difference() {
            cylinder(h = collar_height, d = collar_diam);
            translate([0, 0, -0.1])
                cylinder(h = collar_height + 0.2, d = collar_diam - 2 * t);
        }

        // Knurled grip ring (decorative)
        translate([0, 0, collar_height * 0.3])
            difference() {
                cylinder(h = collar_height * 0.4, d = collar_diam + 2);
                cylinder(h = collar_height * 0.4, d = collar_diam - 0.1);
                for (i = [0 : 35]) {
                    rotate([0, 0, i * 10])
                        translate([collar_diam / 2 + 0.5, 0, 0])
                            cylinder(h = collar_height, d = 1.5);
                }
            }
    }
}


// ── Bill of Materials ───────────────────────────────────
// 1. lamp_base (lamp_base) — diameter=130, height=18, stem_hole_diam=12, chamfer=2
// 2. lamp_arm (lamp_arm) — stem_diam=10, straight_height=260, curve_radius=55, joint_diam=18, collar_diam=18
// 3. lamp_shade (lamp_shade) — top_diam=52, bottom_diam=115, height=85, thickness=1.5, collar_height=10

// ── Assembly ────────────────────────────────────────────

// Part: lamp_base (lamp_base)
color("DarkGray")
translate([0, 0, 0])
  lamp_base(diameter=130, height=18, stem_hole_diam=12, chamfer=2, fn=128);

// Part: lamp_arm (lamp_arm)
color("Silver")
translate([0, 0, 18])
  lamp_arm(stem_diam=10, straight_height=260, curve_radius=55, joint_diam=18, collar_diam=18, collar_height=6, fn=64);

// Part: lamp_shade (lamp_shade)
color("Goldenrod")
translate([22.69, 0, 422.3])
rotate([180, 19.89, 180])
  lamp_shade(top_diam=52, bottom_diam=115, height=85, thickness=1.5, collar_height=10, collar_diam=22, rim_height=3, fn=128);
