from __future__ import annotations

from typing import Any

from scadgen.types import ParameterDef, Template


class SCADRenderer:
    def render(self, template: Template, params: dict[str, Any]) -> str:
        source = self._strip_trailing_calls(template.source_code)
        customizer_block = self._build_customizer_block(template, params)
        call_line = self._build_call_line(template, params)
        derived_block = self._build_derived_block(template, params)

        parts = [
            self._build_header(template),
            customizer_block,
            derived_block,
            source.rstrip(),
            "",
            call_line,
            "",
        ]
        return "\n".join(parts)

    def _build_header(self, template: Template) -> str:
        lines = [
            f"// Generated by SCADgen v0.1.0",
            f"// Template: {template.template_id}",
            f"// {template.description}",
            "",
        ]
        return "\n".join(lines)

    def _build_customizer_block(
        self, template: Template, params: dict[str, Any]
    ) -> str:
        if not template.parameters:
            return ""

        lines = ["/* [Parameters] */"]
        for p in template.parameters:
            value = params.get(p.name, p.default)
            formatted = self._format_value(value, p.type)
            comment = p.description or p.name
            slider = self._slider_annotation(p)
            if slider:
                lines.append(f"{p.name} = {formatted};  // {comment} {slider}")
            else:
                lines.append(f"{p.name} = {formatted};  // {comment}")
        lines.append("")
        return "\n".join(lines)

    def _build_derived_block(
        self, template: Template, params: dict[str, Any]
    ) -> str:
        derived = template.compute_derived(params)
        if not derived:
            return ""
        lines = ["/* [Derived Values] */"]
        for name, value in derived.items():
            display_name = name.replace("_", " ")
            lines.append(f"// {display_name} = {value:.4g} mm")
        lines.append("")
        return "\n".join(lines)

    def _build_call_line(self, template: Template, params: dict[str, Any]) -> str:
        args = []
        for p in template.parameters:
            args.append(f"{p.name}={p.name}")
        return f"{template.module_name}({', '.join(args)});"

    def _strip_trailing_calls(self, source: str) -> str:
        lines = source.rstrip().splitlines()
        while lines and not lines[-1].strip():
            lines.pop()
        meta_end_seen = False
        cleaned = []
        for line in lines:
            if "SCADGEN_META_END" in line:
                meta_end_seen = True
                cleaned.append(line)
                continue
            cleaned.append(line)
        return "\n".join(cleaned)

    def _format_value(self, value: Any, param_type: str) -> str:
        if param_type == "bool":
            return "true" if value else "false"
        if param_type == "int":
            return str(int(float(value)))
        if param_type == "float":
            return f"{float(value):.4g}"
        if param_type == "string":
            return f'"{value}"'
        return str(value)

    def _slider_annotation(self, p: ParameterDef) -> str:
        if p.type not in ("int", "float") or p.min is None or p.max is None:
            return ""
        if p.type == "int":
            return f"[{int(p.min)}:1:{int(p.max)}]"
        step = max(0.1, (p.max - p.min) / 100)
        return f"[{p.min}:{step:.2g}:{p.max}]"
